### ISSUE TITLE
根据qps自动调节抓包率

### ISSUE THREAD

**Issue by zr-hebo** [zr-hebo/sniffer-agent#13]
如题，sniffer可以动态的调整抓包率，但是调整的依据尚不明确，sniffer是否可以提供一个实时qps查询的功能，之后用户根据实时的qps值调整抓包率

**Comment by TDavid2509** [comment]
sniffer手动调节抓包率的设置在哪啊？比如说设置最大值，最小值，即使sniffer允许自动调节，我们能否设置一个自动调节的范围。

**Comment by zr-hebo** [comment]
@TDavid2509 ，可以查看文档介绍：https://github.com/zr-hebo/sniffer-agent/blob/master/docs/capture_rate.md
