### ISSUE TITLE
客户端PORT抓取好像不准确，而且有时候执行的SQL为什么db和用户等都是null

### ISSUE THREAD

**Issue by runblood** [zr-hebo/sniffer-agent#21]
![C482A5D2-502A-460a-8EE2-6C79617DE392](https://user-images.githubusercontent.com/6355703/97658116-7b45d700-1aa6-11eb-9d36-b52c38706895.png)

1、看上边的图，实际执行的SQL，在db和用户列却都是为null；
2、而且客户端的端口为3306

帮忙看下。

**Comment by zr-hebo** [comment]
建立连接之后开始抓取，无法获得连接信息，需要先开启抓包服务，再建立连接

**Comment by zr-hebo** [comment]
客户端的端口为3306不对吗？可以通过参数 --port指定监听端口

**Comment by runblood** [comment]
> 客户端的端口为3306不对吗？可以通过参数 --port指定监听端口

客户端连接上的port怎么是3306呢？

**Comment by runblood** [comment]
> 建立连接之后开始抓取，无法获得连接信息，需要先开启抓包服务，再建立连接

那prd环境 长连接的服务，岂不都要重启才能生效？？

**Comment by zr-hebo** [comment]
必须账号密码的场景，可以使用 --strict_mode=true --admin_user=root --admin_passwd=123456，指定查询的账号密码去服务端查询连接信息

**Comment by zr-hebo** [comment]
> > 建立连接之后开始抓取，无法获得连接信息，需要先开启抓包服务，再建立连接
> 
> 那prd环境 长连接的服务，岂不都要重启才能生效？？

必须账号密码的场景，可以使用 --strict_mode=true --admin_user=root --admin_passwd=123456，指定查询的账号密码去服务端查询连接信息

**Comment by zr-hebo** [comment]
> 客户端的端口为3306不对吗？可以通过参数 --port指定监听端口

可

**Comment by zr-hebo** [comment]
> > 客户端的端口为3306不对吗？可以通过参数 --port指定监听端口
> 
> 客户端连接上的线程 端口怎么是3306呢？

哦，应该是没有获取连接信息，使用了默认端口

**Comment by runblood** [comment]
> > > 建立连接之后开始抓取，无法获得连接信息，需要先开启抓包服务，再建立连接
> > 
> > 
> > 那prd环境 长连接的服务，岂不都要重启才能生效？？
> 
> 必须账号密码的场景，可以使用 --strict_mode=true --admin_user=root --admin_passwd=123456，指定查询的账号密码去服务端查询连接信息

没有host信息，要是不是localhost咋连接啊，就会报错：
ERRO[0003] query user and db from mysql failed <-- query row failed <-- query rows on localhost:3306 failed <-- Error 1045: Access denied for user 'admin'@'::1' (using password: YES)

**Comment by runblood** [comment]
DEBU[0009] receive an unexpect packet
INFO[0009] expect receive size is bigger than max deal size: 131072
INFO[0009] expect receive size is bigger than max deal size: 131072
INFO[0009] expect receive size is bigger than max deal size: 131072

这个问题好像也是存在，类似https://github.com/zr-hebo/sniffer-agent/issues/18  有空维护下项目代码，设计的很不错的，别丢下了。

**Comment by DBAyan** [comment]
这个问题还在吧

**Comment by zr-hebo** [comment]
> 

可能是您那边执行的 SQL比较大吧，最新代码可以通过 --max_packet_length参数，设置这个数值大小

**Comment by zr-hebo** [comment]
> 

可能是您那边执行的 SQL比较大吧，最新代码可以通过 --max_packet_length参数，设置这个数值大小
