### ISSUE TITLE
go build需要输入github账号密码

### ISSUE THREAD

**Issue by liuxinwang** [zr-hebo/sniffer-agent#24]
执行go buid：
xxxx
Username for 'https://github.com': 
Password for 'https://github.com': 
xxxx

**Comment by zr-hebo** [comment]
不太清楚您的操作步骤，git clone下来直接 build即可

**Comment by DBAyan** [comment]
我也需要GitHub的账号密码 
![image](https://user-images.githubusercontent.com/50700896/142996194-716ab786-3072-4fcf-9355-8d261188671d.png)

**Comment by zr-hebo** [comment]
> 我也需要GitHub的账号密码 ![image](https://user-images.githubusercontent.com/50700896/142996194-716ab786-3072-4fcf-9355-8d261188671d.png)

这个项目需要关闭 GO111MODULE，关闭之后再试试
