### ISSUE TITLE
go build失败

### ISSUE THREAD

**Issue by liuxinwang** [zr-hebo/sniffer-agent#25]
go version go1.12.17 linux/amd64:
cannot find module providing package github.com/zr-hebo/validator

**Comment by zr-hebo** [comment]
关闭 go mod应该可以：go env -w GO111MODULE="off"

**Comment by liuxinwang** [comment]
用了v1.3版本
export GOPROXY=https://goproxy.io
export GO111MODULE=on
go build -mod=vendor
这样成功build了

**Comment by zr-hebo** [comment]
> 用了v1.3版本
> export GOPROXY=https://goproxy.io
> export GO111MODULE=on
> go build -mod=vendor
> 这样成功build了

应该是 go mod的问题，本项目中使用了一些基础包，这些包在国内可能拉取不了，因此没有加 go mod，而是把它们放到了 vendor中。
