### ISSUE TITLE
执行运行失败

### ISSUE THREAD

**Issue by liuxinwang** [zr-hebo/sniffer-agent#26]
[root@host-172-16-10-12 sniffer-agent-1.2.0]# ./sniffer-agent --interface=eth0 --port=3307 --export_type=cli
set config capture_packet_rate: 1
INFO[0000] parsed local ip address:172.16.10.12         
set config capture_packet_rate: 1
panic: package size bigger than max buffer size need deal:0

goroutine 24 [running]:
github.com/zr-hebo/sniffer-agent/util.(*SliceBufferPool).DequeueWithInit(0xc0000a8fe0, 0x54, 0x0, 0x0, 0x0)
        /usr/local/sniffer-agent-1.2.0/util/cache_pool.go:43 +0x165
github.com/zr-hebo/sniffer-agent/session-dealer/mysql.(*MysqlSession).readFromClient(0xc000174000, 0x64ab3a25, 0xc000258042, 0x58, 0xffbe)
        /usr/local/sniffer-agent-1.2.0/session-dealer/mysql/session.go:182 +0xe6
github.com/zr-hebo/sniffer-agent/session-dealer/mysql.(*MysqlSession).ReceiveTCPPacket(0xc000174000, 0xc00016c060)
        /usr/local/sniffer-agent-1.2.0/session-dealer/mysql/session.go:91 +0x90
github.com/zr-hebo/sniffer-agent/capture.readToServerPackage(0x0, 0x0, 0xc000172020, 0xd2e8, 0xc0001648c0, 0xc0000872c0, 0x0, 0x0)
        /usr/local/sniffer-agent-1.2.0/capture/network.go:295 +0x19b
github.com/zr-hebo/sniffer-agent/capture.(*networkCard).parseTCPPackage(0xc0000a9480, 0xb3ac00, 0xc0000ecc60, 0x0)
        /usr/local/sniffer-agent-1.2.0/capture/network.go:212 +0x22c
github.com/zr-hebo/sniffer-agent/capture.(*networkCard).listenNormal.func1(0xc0000a9480)
        /usr/local/sniffer-agent-1.2.0/capture/network.go:164 +0x41a
created by github.com/zr-hebo/sniffer-agent/capture.(*networkCard).listenNormal
        /usr/local/sniffer-agent-1.2.0/capture/network.go:107 +0x3f

**Comment by zr-hebo** [comment]
bug已修复，https://github.com/zr-hebo/sniffer-agent/pull/28

**Comment by liuxinwang** [comment]
> bug已修复，#28

v1.3.0测试可以运行了，偶发会有以下报错信息，但是不影响运行
ERRO[0011] parse auth info failed <-- malform packet error

**Comment by zr-hebo** [comment]
> > bug已修复，#28
> 
> v1.3.0测试可以运行了，偶发会有以下报错信息，但是不影响运行
> ERRO[0011] parse auth info failed <-- malform packet error

这个是解析建立连接阶段的鉴权信息解析失败了，不影响使用。不知道您连接的数据版本是什么呢？

**Comment by liuxinwang** [comment]
> > > bug已修复，#28
> > 
> > 
> > v1.3.0测试可以运行了，偶发会有以下报错信息，但是不影响运行
> > ERRO[0011] parse auth info failed <-- malform packet error
> 
> 这个是解析建立连接阶段的鉴权信息解析失败了，不影响使用。不知道您连接的数据版本是什么呢？

5.5的版本
