### ISSUE TITLE
无任何输出，感觉没抓到

### ISSUE THREAD

**Issue by halodba** [zr-hebo/sniffer-agent#31]
[root@test_5_186 sniffer-agent]# ./sniffer-agent --interface=ens160 --port=3306 --log_level=debug   --capture_packet_rate=1000  --export_type=cli   --max_packet_length=13107200
set config capture_packet_rate: 1
INFO[0000] parsed local ip address:10.6.5.186           
INFO[0000] begin listen                                 
set config capture_packet_rate: 1000
另一边模拟数据库登录，执行sql，但sniffer-agent后面无任何输出，

**Comment by halodba** [comment]
mysql 5.7,centos 7.5,sniffer-agent 1.3.0

**Comment by zr-hebo** [comment]
高版本的 mysql client连接默认添加了 SSL模式，可以尝试 mysql client使用 --ssl-mode=DISABLED连接，然后看能不能抓到SQL。

**Comment by aaronwu** [comment]
> 

打算支持ssl链接的抓包吗？

**Comment by aaronwu** [comment]
> 高版本的 mysql client连接默认添加了 SSL模式，可以尝试 mysql client使用 --ssl-mode=DISABLED连接，然后看能不能抓到SQL。

打算支持ssl链接的抓包吗？

**Comment by zr-hebo** [comment]
> 

这个功能有一定的难度，目前还没打算。如果有其他比较好的方案，欢迎一起讨论或者提交 PR。
