### ISSUE TITLE
能否提供一个编译好的包

### ISSUE THREAD

**Issue by kakamylove** [zr-hebo/sniffer-agent#6]
能否提供一个编译后可执行的包？或者提供一下go env的配置参数？
谢啦

**Comment by zr-hebo** [comment]
这个项目没有复杂的依赖，直接按照文档说明就可以编译了。你的编译遇到什么问题了？

**Comment by DBAyan** [comment]
同求 编译一直报错

**Comment by zr-hebo** [comment]
已将 CentOS7.4下编译的可执行文件添加到到 v1.3.0中
